# [[keyboard.bindings]]
# chars = "\u001BF"
# key = "Right"
# mods = "Alt"
# 
# [[keyboard.bindings]]
# chars = "\u001BB"
# key = "Left"
# mods = "Alt"

[keyboard]
bindings = [
  # https://github.com/alacritty/alacritty/issues/3586
  { key = "Slash", mods = "Control", chars = "\u001f" },
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
]

[font]
normal = { family = "MartianMono Nerd Font", style = "Regular" }

[general]
live_config_reload = true

[window]
startup_mode = "Windowed"
decorations = "Full"
opacity = 0.8
blur = true
padding = { x = 4, y = 1 }

[cursor]
style = { shape = "Underline", blinking = "Always" }
blink_interval = 1000
